/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp inteface.xml -a mdecoratordbusadaptor -i mabstractappinterface.h -c MDecoratorDBusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mdecoratordbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MDecoratorDBusAdaptor
 */

MDecoratorDBusAdaptor::MDecoratorDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MDecoratorDBusAdaptor::~MDecoratorDBusAdaptor()
{
    // destructor
}

void MDecoratorDBusAdaptor::setActions(IPCActionList actions, uint window)
{
    // handle method call com.nokia.MDecorator.setActions
    QMetaObject::invokeMethod(parent(), "setActions", Q_ARG(IPCActionList, actions), Q_ARG(uint, window));
}

