######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 17 14:59:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += showwin.cpp
