######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 15 10:41:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
