######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 15 10:41:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../decorators/libdecorator
QMAKE_LFLAGS += -L../../decorators/libdecorator #to link to the library of the repo not of the system
LIBS += -ldecorator
QT += dbus

# Input
SOURCES += main.cpp
